services:
  app:
    container_name: award-generator
    volumes:
      - .:/var/project
      - ./.docker/app/php/php.ini-development:/usr/local/etc/php/php.ini
      - ./.docker/app/nginx/http.d/default.conf:/etc/nginx/http.d/default.conf
      - ./.docker/app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/app/fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./.docker/app/fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    ports:
      - 80:80
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    environment:
      SYMFONY_ENV: "dev"
      ENV: "dev"
    depends_on:
      - database

  database:
    image: mariadb:10.11.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql:rw
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

volumes:
  db-data:
    driver: local