name: CI

on: push

jobs:
  phpmd:
    name: Quality and Codestyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-scripts

      - name: Run PHPMD
        run: vendor/bin/phpmd src,tests text phpmd.xml

      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=phpcs.xml.dist

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.dist.neon

      - name: Run psalm
        run: vendor/bin/psalm --config=psalm.xml